### ISSUE TITLE
バージョンアップによる不具合について

### ISSUE THREAD

**Issue by ghost** [negokaz/vscode-markdown-console#6]
VSCodeをバージョン1.94以上にして、コンソールを有効化にするボタンを押下すると動かなくなりました。

エラーメッセージは以下
```
024-10-09 09:50:33.647 [info] ExtensionService#_doActivateExtension negokaz.markdown-console, startup: false, activationEvent: 'onLanguage:markdown'
2024-10-09 09:50:34.185 [error] Activating extension negokaz.markdown-console failed due to an error:
2024-10-09 09:50:34.185 [error] TypeError: Cannot read properties of undefined (reading 'require')
	at 17543 (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:691990)
	at n (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:1860878)
	at 88572 (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:668688)
	at n (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:1860878)
	at 91618 (c:\○○○○\tkmshkt\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:671683)
	at n (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:1860878)
	at 95468 (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:640337)
	at n (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:1860878)
	at 7203 (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:651480)
	at n (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:1860878)
	at 55718 (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:653310)
	at n (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:1860878)
	at c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:1861309
	at Object.<anonymous> (c:\Users\○○○○\.vscode\extensions\negokaz.markdown-console-0.10.2\dist\extension.js:2:1861336)
	at Module._compile (node:internal/modules/cjs/loader:1373:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at e._load (file:///c:/Users/○○○○/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///c:/Users/○○○○/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///c:/Users/○○○○/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at hB.xb (file:///c:/Users/○○○○/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23767)
	at async Promise.all (index 0)
2024-10-09 09:50:34.185 [info] ExtensionService#_doActivateExtension yzhang.markdown-all-in-one, startup: false, activationEvent: 'onLanguage:markdown'
```

**Comment by negokaz** [comment]
@ghost 
お待たせいたしました。バージョン `0.10.3` で不具合を修正しました。
バージョンアップしても問題が解消しないなどあれば、issue を再度 Open してお知らせください。
